theme: jekyll-theme-slate
title: SCANeR Software resources
show_downloads: true
plugins:
  - jemoji
github:
  repository_url: https://github.com/AVSGuillaume/Samples-Pack/tree/2021.2
  zip_url: https://github.com/AVSGuillaume/Samples-Pack/archive/refs/heads/2021.2.zip
  youtube_url: https://www.youtube.com/channel/UCYNNe9SaA3LjCFb2qXmhkoA
