theme: jekyll-theme-slate
title: SCANeR Quick Starts
description : Resources to discover SCANeR
show_downloads: false
plugins:
  - jemoji
github:
  repository_url: https://github.com/AVSimulation/SCANeR-Quick-Starts/tree/Published
  avs_url: https://www.avsimulation.com
  events_url: https://www.avsimulation.com/events/
  youtube_url: https://www.youtube.com/channel/UCYNNe9SaA3LjCFb2qXmhkoA

groups:
  -
    name: Get Ready
    next: Get Started
  -
    name: Get Started
    prev: Get Ready
    next: First Simulation
  - 
    name: Workspace
    prev: Get Started
    next: First Simulation
  -
    name: First Simulation
    prev: Get Started
    next: Intermediate
  -
    name: Intermediate
    prev: First Simulation
  -
    name: Samples Pack
    prev: Get Ready
